### ISSUE TITLE
Provide input to code being executed

### ISSUE THREAD

**Issue by gadsater** [FrenchMasterSword/RTFMbot#11]
It seems that the project uses tio.run to compile and execute programs. This website allows programs to accept input from stdin. Is there a way possible to extend the do run command so that we can provide inputs too?

For example,
The current syntax for executing a program is - do run <language> <code>
There could be an additional command included that can support input. The syntax for that command could be - do run <language> <code> <input>

Example command usage:
do run python
```
n = input()
print(n)
```
```
3
```

Command output:
3

**Comment by FrenchMasterSword** [comment]
You can already provide input in the command
see an example in https://github.com/FrenchMasterSword/RTFMbot/wiki/Coding-module#run

**Comment by gadsater** [comment]
Oh, thanks a lot! Sorry that I didn't check the docs previously 😅
