### ISSUE TITLE
add mips assembly to rtfmbot

### ISSUE THREAD

**Issue by Kreijstal** [FrenchMasterSword/RTFMbot#12]
Hi, we're learning MIPS on our university, and I know that tio.run can run mips, would it be possible to add it to RTFM? thank you.

**Comment by FrenchMasterSword** [comment]
You are already able to use any language you can use on tio.run. The language name you have to use is the name of the anchor (after the #) in its url. For `MIPS`, the URL is https://tio.run/#spim, thus you have to use `spim`. (It's SPIM, the MIPS simulator).

Example: (used `mips` for the syntax coloration)
![image](https://user-images.githubusercontent.com/33038089/84263960-b3ad3e80-ab20-11ea-8e77-2a1a59e53a6d.png)
