### ISSUE TITLE
`do run` command responding twice

### ISSUE THREAD

**Issue by isaa-ctaylor** [FrenchMasterSword/RTFMbot#20]
When running the `do run` command, the bot is responding twice. Example: https://isaac.likes-throwing.rocks/ynav9Y.png

**Comment by maniac-en** [comment]
@isaa-ctaylor  I can not reproduce the same!

Preview:
![image](https://i.imgur.com/akONAug.png)

Can you maybe give some more info on the issue?
Did it happen only once or does it happen every time?
Are you using the publicly hosted server or is it your own build?

CC @FrenchMasterSword I like your project and just feel like contributing in any way possible `:)`

**Comment by isaa-ctaylor** [comment]
It no longer happens... oh well
